feat(drivers): add scrypt driver
adonisjs/hash pull request #9
Opened 2022-10-17 18:48 UTC by RomainLanz

Hey there! 👋🏻 

This PR adds the native `scrypt` hash algorithm to hash passwords.

I would recommend that we use it as default when installing a new application.

2022-10-17 20:32 UTC, targos commented
Why not argon2 as the default?

2022-10-17 21:15 UTC, RomainLanz commented
> Why not argon2 as the default?

That would be the best, but it means we have to pre-install the `argon2` package on the userland code for any installation of Adonis. Meaning also compiling its code (since it is not JS based).

`scrypt` is built directly in Node. No need to pre-install anything, and you can use it without changing the footprint of the user application

2022-10-18 04:50 UTC, thetutlage commented
Can you open another PR for the docs to mention that one should be using `argon2` in production. 

It can be added to https://docs.adonisjs.com/guides/security/hashing and the https://docs.adonisjs.com/guides/deployment docs

2022-10-18 20:16 UTC, RomainLanz commented
Done! Also, PRing the `core` module to change the default driver.

Before merging, should we rename options `keylen` to `keyLength` and `maxmem` to `maxMemory`?
I used the naming in Node, but using complete naming may be more accessible.

2022-10-19 16:05 UTC, RomainLanz commented
After a discussion with @rault-a, we can remove `@kdf/salt` and `tsse` by using native code.
I will update the PR and migrate the other drivers.

2022-10-19 16:47 UTC, thetutlage commented
Looking forward to it :)

> Before merging, should we rename options keylen to keyLength and maxmem to maxMemory?

Wouldn't this be a breaking change?

2022-10-19 16:54 UTC, RomainLanz commented
> Wouldn't this be a breaking change?

Those options are only used in `scrypt`, so it will not break anything.

2022-10-19 19:16 UTC, RomainLanz commented
Should be good!

2022-10-26 07:38 UTC, thetutlage requested changes

2022-10-26 07:38 UTC, thetutlage commented on src/Drivers/Scrypt.ts
> +      return Promise.reject(new TypeError('The param section cannot be empty'))
Can't we just thrown the exception vs creating another promise?

2022-10-26 07:38 UTC, thetutlage commented on test/scrypt.spec.ts
> +test.group('Scrypt', () => {
We will need more tests covering all the failure cases as well

2022-10-26 08:46 UTC, RomainLanz commented
Done!

2022-10-31 00:36 UTC, thetutlage commented
Looks great. Just for my personal knowledge. Are they are any recommendations guides on how to best use Scrypt? And what should be the default config for `blockSize` or `parallelization`?

2022-10-31 08:08 UTC, RomainLanz commented
We could increase the key length to `128` bits instead of `64` to be more resilient on brute force attacks, but I believe the default value proposed by Node.js is more than enough.

Everything is a trade-off regarding the server you will run the code on. Default values should run anywhere.

2022-11-10 05:28 UTC, merged

2022-11-10 05:28 UTC, thetutlage commented
Looks great 👍